# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509ed6f24a5fb97e1dcb3825abb8f4a9484f23372ee565100ed87a78686904fbf72c5fc222a1e97f6419900462a714a75ea2838ebc69ea1c93ad186c5cda7de8

test:
  secret_key_base: bdde1669f16b3e5362b73e8b085e76147f279f05f93a95e265f780749e762ea2078c5e50b63d18d8b727bc9f45e7eeac110c794a05a18ae9cdca899fb90b576d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
